name: slack-notification

on: [push, issues]

jobs:
  slack-notification:
    runs-on: ubuntu-20.04
    name: Sends a message to Slack on push and issue

    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@master
        id: send-message
        with:
          slack-bot-user-oauth-access-token: ${{ xoxb-1861292072304-1834494603989-2DMwk6sY8NV30tnQmCxrX03B }}
          slack-channel: automation
          slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}" 🤓

      - name: Result from "Send Slack Message"
        run: echo "${{ steps.send-message.outputs.slack-result }}"
